### ISSUE TITLE
"File may be damaged or incomplete" when starting with a list of Object IDs

### ISSUE THREAD

**Issue by bengips** [jsfenfen/irsx_cookbook#3]
When starting with CSV that has Object IDs (sourced from Open990.org), Python returns the following error:

rsx.filing.InvalidXMLException: 'Return' element not located in [file path] Python38\site-packages\irsx\XML\201920779349100000_public.xml
File may be damaged or incomplete.
Try erasing this file and downloading again.

The script was working great when I was using the index file created by Part 1 of the cookbook example! Unfortunately, it missed e-filed records from some of the organizations I was interested in pursuing further (possibly due to the errors in the index files themselves?), so I looked up their object IDs and tried to create a test CSV modeling after the one created in Part 1. When I look in the XML folder within the IRSx package, I see that these files are downloaded and viewable just like the ones the script worked for previously. I'm stumped as to where this error might have come from!

[ContractorsFromList.txt](https://github.com/jsfenfen/irsx_cookbook/files/5638432/ContractorsFromList.txt)

**Comment by jsfenfen** [comment]
hey @bengips thanks for reporting this. I just tried running this, and it appears that there is no tax return available, e.g. the actual file you are trying to parse is an amazon 404 type message, see below. That said,  this is really fascinating since in theory these files aren't removed. Do you happen to know when this file was available? I've also heard that not all files are captured in the index files (I tend to sync a directory against amazon directly) but that sounds a bit frightening if these files are going away. 

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message>
<Key>201920779349100000_public.xml</Key><RequestId>89C3D86E6E15AC3B</RequestId>
<HostId>snjdiJLH+g7e8ULgXHCZ2FiWi9IPcbO5PFL7GDXIdimzkcXfFmxDfLjfyoEpCXl+6AvUUtUJ2UM=</HostId></Error>

**Comment by bengips** [comment]
Thank you for following up @jsfenfen. That was my first thought as well, but I can view the raw XML in my browser at this link: https://s3.amazonaws.com/irs-form-990/201920779349100112_public.xml. Nonetheless, this does seem like an issue primarily associated with this particular filing - in an related search recently, I noticed Candid also had trouble processing their filing, so maybe there is some permission that is denied for that particular filing? After spot checking a few more, this seems to be the only one one my list with an XML filing that didn't get captured by the script. I was concerned about the indices as well, particularly after reading this article: https://appliednonprofitresearch.com/posts/2020/06/skip-the-irs-990-efile-indices/. I tried using the script from the article to set up my own index to query for the orgs I was looking for, but it was a bit too complex for me to figure out. Either way, this seems to be an isolated problem and I think the indices seem to have worked fine for my purposes. Thanks again for looking into it!

**Comment by jsfenfen** [comment]
Huh, that's really odd. I just tried it again, and it ran fine from the
CLI. Not totally sure what to make of this.

**Comment by jsfenfen** [comment]
But nonetheless love that it comes down to a three-letter-ending-in-S acronym sheistiness Rorschach: IRS or AWS? Without debugging further, maybe it's just best to assume it's a waveform simultaneously existing in both? That prob won't fly with the IRS, come to think of it.
